version: '3'

services:
  
  redis:
    image: "redis:alpine"
  
  beat:
    build: .
    working_dir: /app
    command: celery -A tasks beat --loglevel=info
    volumes:
      - .:/app
  
  worker_fns:
    build: .
    working_dir: /app
    command: celery -A tasks worker --loglevel=info --concurrency=1 -Q fns
    volumes:
      - .:/app
  
  worker_ds:
    build: .
    working_dir: /app
    command: celery -A tasks worker --loglevel=info --concurrency=2 -Q ds
    volumes:
      - .:/app

  worker_ps:
    build: .
    working_dir: /app
    command: celery -A tasks worker --loglevel=info --concurrency=5 -Q ps
    volumes:
      - .:/app
  
  flower:
    build: .
    working_dir: /app
    command: celery -A tasks flower
    ports:
      - "5555:5555"
    volumes:
      - .:/app

  visualizer:
    build: .
    working_dir: /app
    command: uvicorn api:app --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

